//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Controls for Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlsforPlayer : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlsforPlayer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls for Player"",
    ""maps"": [
        {
            ""name"": ""Inv"",
            ""id"": ""fd34008b-80e7-426d-97d4-7c82c44f2dfd"",
            ""actions"": [
                {
                    ""name"": ""Fire1"",
                    ""type"": ""Button"",
                    ""id"": ""fd1e9d33-dc43-4419-b81d-74f46283fac0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""5ed0ff00-4926-4efc-a969-e399a0c91f33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressPick"",
                    ""type"": ""Button"",
                    ""id"": ""137fa85d-f5ab-4b53-b7f3-1da9092e75c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press,Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""249f10df-dcd2-4d2a-b7a2-a5310ed10354"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1442667d-a526-4eb4-9b71-7e1666b28729"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad86e4db-23c8-4aac-9036-2eff151e3b10"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressPick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Actions"",
            ""id"": ""e0f5a95b-511f-4b07-a28e-fa89eb759e3c"",
            ""actions"": [
                {
                    ""name"": ""Glide"",
                    ""type"": ""Button"",
                    ""id"": ""81c37c7b-46ca-44df-89ad-1757458b57c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dive"",
                    ""type"": ""Button"",
                    ""id"": ""63fb4c82-2fc1-4970-b6bb-fca2cb8c73b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GlideLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e8203e8b-3fc1-4b66-9508-615a9eb92162"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GlideRight"",
                    ""type"": ""Button"",
                    ""id"": ""2fca163b-c2dd-47df-ba3f-2bfd8aa1c8de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateHat"",
                    ""type"": ""Button"",
                    ""id"": ""6c17a212-3d76-41d5-9ae8-652fad329c43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchHat"",
                    ""type"": ""Button"",
                    ""id"": ""9c9d96d4-3c91-49af-a09f-88044214b080"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""33451d84-4d40-4673-9264-327a2b73831d"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Glide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c984d088-ea9b-4b9b-9b66-f62508c13fdd"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90ac33f5-f896-4b4f-8a80-74b6d8058514"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GlideLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc2caacf-93cc-450a-824a-6ee2566ecbad"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GlideRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae1ca6ca-246b-44a2-bbab-a2f84706bb38"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateHat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40e14eda-2213-43c2-a0eb-512397f8b8a9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Inv
        m_Inv = asset.FindActionMap("Inv", throwIfNotFound: true);
        m_Inv_Fire1 = m_Inv.FindAction("Fire1", throwIfNotFound: true);
        m_Inv_Drop = m_Inv.FindAction("Drop", throwIfNotFound: true);
        m_Inv_PressPick = m_Inv.FindAction("PressPick", throwIfNotFound: true);
        // Actions
        m_Actions = asset.FindActionMap("Actions", throwIfNotFound: true);
        m_Actions_Glide = m_Actions.FindAction("Glide", throwIfNotFound: true);
        m_Actions_Dive = m_Actions.FindAction("Dive", throwIfNotFound: true);
        m_Actions_GlideLeft = m_Actions.FindAction("GlideLeft", throwIfNotFound: true);
        m_Actions_GlideRight = m_Actions.FindAction("GlideRight", throwIfNotFound: true);
        m_Actions_ActivateHat = m_Actions.FindAction("ActivateHat", throwIfNotFound: true);
        m_Actions_SwitchHat = m_Actions.FindAction("SwitchHat", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Inv
    private readonly InputActionMap m_Inv;
    private IInvActions m_InvActionsCallbackInterface;
    private readonly InputAction m_Inv_Fire1;
    private readonly InputAction m_Inv_Drop;
    private readonly InputAction m_Inv_PressPick;
    public struct InvActions
    {
        private @ControlsforPlayer m_Wrapper;
        public InvActions(@ControlsforPlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fire1 => m_Wrapper.m_Inv_Fire1;
        public InputAction @Drop => m_Wrapper.m_Inv_Drop;
        public InputAction @PressPick => m_Wrapper.m_Inv_PressPick;
        public InputActionMap Get() { return m_Wrapper.m_Inv; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InvActions set) { return set.Get(); }
        public void SetCallbacks(IInvActions instance)
        {
            if (m_Wrapper.m_InvActionsCallbackInterface != null)
            {
                @Fire1.started -= m_Wrapper.m_InvActionsCallbackInterface.OnFire1;
                @Fire1.performed -= m_Wrapper.m_InvActionsCallbackInterface.OnFire1;
                @Fire1.canceled -= m_Wrapper.m_InvActionsCallbackInterface.OnFire1;
                @Drop.started -= m_Wrapper.m_InvActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_InvActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_InvActionsCallbackInterface.OnDrop;
                @PressPick.started -= m_Wrapper.m_InvActionsCallbackInterface.OnPressPick;
                @PressPick.performed -= m_Wrapper.m_InvActionsCallbackInterface.OnPressPick;
                @PressPick.canceled -= m_Wrapper.m_InvActionsCallbackInterface.OnPressPick;
            }
            m_Wrapper.m_InvActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Fire1.started += instance.OnFire1;
                @Fire1.performed += instance.OnFire1;
                @Fire1.canceled += instance.OnFire1;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
                @PressPick.started += instance.OnPressPick;
                @PressPick.performed += instance.OnPressPick;
                @PressPick.canceled += instance.OnPressPick;
            }
        }
    }
    public InvActions @Inv => new InvActions(this);

    // Actions
    private readonly InputActionMap m_Actions;
    private IActionsActions m_ActionsActionsCallbackInterface;
    private readonly InputAction m_Actions_Glide;
    private readonly InputAction m_Actions_Dive;
    private readonly InputAction m_Actions_GlideLeft;
    private readonly InputAction m_Actions_GlideRight;
    private readonly InputAction m_Actions_ActivateHat;
    private readonly InputAction m_Actions_SwitchHat;
    public struct ActionsActions
    {
        private @ControlsforPlayer m_Wrapper;
        public ActionsActions(@ControlsforPlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Glide => m_Wrapper.m_Actions_Glide;
        public InputAction @Dive => m_Wrapper.m_Actions_Dive;
        public InputAction @GlideLeft => m_Wrapper.m_Actions_GlideLeft;
        public InputAction @GlideRight => m_Wrapper.m_Actions_GlideRight;
        public InputAction @ActivateHat => m_Wrapper.m_Actions_ActivateHat;
        public InputAction @SwitchHat => m_Wrapper.m_Actions_SwitchHat;
        public InputActionMap Get() { return m_Wrapper.m_Actions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionsActions set) { return set.Get(); }
        public void SetCallbacks(IActionsActions instance)
        {
            if (m_Wrapper.m_ActionsActionsCallbackInterface != null)
            {
                @Glide.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlide;
                @Glide.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlide;
                @Glide.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlide;
                @Dive.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnDive;
                @Dive.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnDive;
                @Dive.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnDive;
                @GlideLeft.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlideLeft;
                @GlideLeft.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlideLeft;
                @GlideLeft.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlideLeft;
                @GlideRight.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlideRight;
                @GlideRight.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlideRight;
                @GlideRight.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGlideRight;
                @ActivateHat.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnActivateHat;
                @ActivateHat.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnActivateHat;
                @ActivateHat.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnActivateHat;
                @SwitchHat.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnSwitchHat;
                @SwitchHat.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnSwitchHat;
                @SwitchHat.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnSwitchHat;
            }
            m_Wrapper.m_ActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Glide.started += instance.OnGlide;
                @Glide.performed += instance.OnGlide;
                @Glide.canceled += instance.OnGlide;
                @Dive.started += instance.OnDive;
                @Dive.performed += instance.OnDive;
                @Dive.canceled += instance.OnDive;
                @GlideLeft.started += instance.OnGlideLeft;
                @GlideLeft.performed += instance.OnGlideLeft;
                @GlideLeft.canceled += instance.OnGlideLeft;
                @GlideRight.started += instance.OnGlideRight;
                @GlideRight.performed += instance.OnGlideRight;
                @GlideRight.canceled += instance.OnGlideRight;
                @ActivateHat.started += instance.OnActivateHat;
                @ActivateHat.performed += instance.OnActivateHat;
                @ActivateHat.canceled += instance.OnActivateHat;
                @SwitchHat.started += instance.OnSwitchHat;
                @SwitchHat.performed += instance.OnSwitchHat;
                @SwitchHat.canceled += instance.OnSwitchHat;
            }
        }
    }
    public ActionsActions @Actions => new ActionsActions(this);
    public interface IInvActions
    {
        void OnFire1(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnPressPick(InputAction.CallbackContext context);
    }
    public interface IActionsActions
    {
        void OnGlide(InputAction.CallbackContext context);
        void OnDive(InputAction.CallbackContext context);
        void OnGlideLeft(InputAction.CallbackContext context);
        void OnGlideRight(InputAction.CallbackContext context);
        void OnActivateHat(InputAction.CallbackContext context);
        void OnSwitchHat(InputAction.CallbackContext context);
    }
}
